spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car
    username: chhun
    password: chhun
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

rest-url:
  combination: "http://localhost:8000"
  body-mock: ${rest-url.combination}/combination/body/
  engine-mock: ${rest-url.combination}/combination/engine/
  wheel-mock: ${rest-url.combination}/combination/wheel/

random-insert:
  data: false